/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAppointmentById' : IDL.Func([IDL.Nat], [Appointment], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAppointmentById' : IDL.Func([IDL.Nat], [Appointment], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };